apiVersion: apps/v1
kind: Deployment
metadata:
  name: svkd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svkd
  template:
    metadata:
      labels:
        app: svkd
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        effect: "NoSchedule"
      - key: "dedicated"
        operator: "Equal"
        value: "svkd"
        effect: "NoSchedule"
      containers:
      - name: svkd
        image: kennyparsons/svkd
        ports:
        - containerPort: 80  # expose port 80 from the container

---
apiVersion: v1
kind: Service
metadata:
  name: svkd-service
spec:
  selector:
    app: svkd  # match the deployment's labels
  ports:
  - name: http
    port: 31001   # expose port 31001 for the service
    targetPort: 80  # forward traffic to the container's port 80
